version: '3'
services:
  localstack:
    image: "jasonzhang/localstack:jason"
    container_name: "joulepim"
    ports:
      - "4572:4572"
      - "4584:4584"
      - "4569:4569"
      - "4574:4574"
      - "4576:4576"
      - "4578:4578"
      - "4581:4581"
      - "4582:4582"
      - "4585:4585"
      - "4586:4586"
      - "${PORT_WEB_UI-8081}:${PORT_WEB_UI-8081}"
    environment:
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - SERVICES=s3,secretsmanager,dynamodb,lambda,sqs,elasticsearch service,cloudwatch,cloudwatch logs,stepfunctions,cloudformation
      - DEBUG=1
      - DEFAULT_REGION=us-west-2
      - DATA_DIR=/tmp/localstack/data
      - TMPDIR=/private${TMPDIR- }
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'