version: '3'
services:
  localstack:
    image: "jasonzhang/localstack:jason"
    container_name: "joulepim"
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8081}:${PORT_WEB_UI-8081}"
      - "8000:8000"
    environment:
      - SERVICES=${SERVICES- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DEBUG=1
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - TMPDIR=/private${TMPDIR- }
      - LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=_debug_port_
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'